apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command:
      - sh
      - -c
      - 'while true; do date >> /tmp/nfs/index.html; hostname >> /tmp/nfs/index.html; sleep 10; done'
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: nfs-claim
        mountPath: "/tmp/nfs"
  restartPolicy: OnFailure
  volumes:
    - name: nfs-claim
      persistentVolumeClaim:
        claimName: pvc-nsf
  