apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-vol
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-nfs-storage-class
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    path: /mnt/nfs-share
    server: 10.148.0.10